### ISSUE TITLE
Check the SketchApp file against supported version

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#102]
**Describe the solution you'd like**
We need to make sure that the sketchapp file being used, has been created with the right SketchApp supported version (52+)

If the version detected isnt supported by xlayers, we need to run through the fallback parsing.

**Comment by Jefiozie** [comment]
HI @manekinekko, maybe I can have a look at this issue. Is see that there is a `appVersion` where we can check the version from the Sketch file. But I missing the fallback parser part. Can you explain a bit more on this?

**Comment by manekinekko** [comment]
@Jefiozie aweome. thank you!!

So historically, the parser was able to parse SketchApp file created in 43+. But the *.sketch file format seemed to be changing version after version and some properties like the text content are now encoded differently, so we decided to improve the parser and only support recent versions of Sketchapp. 

So, the idea here is to detect the version of in the *.sketchapp file and decide whether:
1. we should support that, which means that we need to patch the parser to extract any useful data (text, color...).
2. we should **not** patch the parser, meaning that we cant extract the data. But make sure the parser doesnt throw errors. Of course, the generated designs would be incomplete and we should inform the user about that.
3. we should completely block unsupported versions (<=51) and inform the user.

Notes:
- So obviously 1) is a little more challenging that the other two but it is the most valuable and inclusive.
- For the issue, I personally was thinking about 2).
- To inform the user,we use a [snackbar](https://material.angular.io/components/snack-bar/overview) component.
- for 3) version detection and blocking could be done [here](https://github.com/xlayers/xlayers/blob/develop/src/app/editor/viewer/lib/sketch-container.component.ts#L69).

Relateds issues: https://github.com/xlayers/xlayers/issues/101 and https://github.com/xlayers/xlayers/issues/98

This issue is also somehow related to https://github.com/xlayers/xlayers/issues/99

Please let me know if you need more help.

**Comment by Jefiozie** [comment]
Great thanks for this information. I will try and implement idea 2. I will refactor a bit so we can use the snackbar from a `Action`.  Do you want me to put this part in a separate PR?

**Comment by Jefiozie** [comment]
@manekinekko , looked at the parsing part when It cannot parse it will show a `console.error ` correct? Do you want me to fix that and use good `Exeception handling` that we can use for this issue or am I missing something 😆

**Comment by manekinekko** [comment]
I think we should not console log errors but if something went wrong, we need to inform the user at the end of the process, that the design was created using an unsupported version so the result may not be accurate.

Also, feel free to review the exception handling. It'd be great to have a centralized Error handling (see https://angular.io/api/core/ErrorHandler)

**Comment by Shikanime** [comment]
I made the parser throw an `SketchUnSupportedError` in my wip sketch parser legacy improvement.  This will then be handled by your current implementation try catch.

**Comment by Jefiozie** [comment]
At the moment it will not affect the parser. But I saw the PR you made maybe its best to change this code to use your changes for the verification of the sketch version?

**Comment by manekinekko** [comment]
example of related issues:
- #153 #147

**Comment by Shikanime** [comment]
#157 and #159 add a version guard and notify the user.
