### ISSUE TITLE
Flaky monaco tabs on first rendering

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#105]
**Describe the bug**
When we generate the code and add it to the monaco editor, the text doesnt show up on the first rendering. We need to switch to another tab and switch back so the text gets re-rendered.

**To Reproduce**
1. load any demo file
2. the UI editor shows up with the generated files (one file per tab)
4. code doest show up at first
5. click on any other tab
6. click back on the first tab, and the code shows up

**Expected behavior**
We need to see the generated code (of the first tab) after the parsing is done and the code editor is populated.

**Comment by manekinekko** [comment]
FYI, this issue seems to have a random behavior.

**Comment by Shikanime** [comment]
I perform some test, mat-tab may be responsible.

**Comment by manekinekko** [comment]
Moved this issue to the backlog.

**Comment by manekinekko** [comment]
Fixed in #164
