### ISSUE TITLE
Allow downloading the generated code as a ZIP file

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#106]
**Describe the solution you'd like**
Allow downloading the generated code as a ZIP file

**Comment by Shikanime** [comment]
I have a good idea related to the navigation menu and that kinda look cool ! I put all related (stackblitz and zip) button in a context menu.

![screencast 2018-12-19 3 pm-32-55](https://user-images.githubusercontent.com/22115108/50226520-a851da80-03a3-11e9-8f22-6b6dfe018a8f.gif)

**Comment by manekinekko** [comment]
I like that. LGTM

**Comment by manekinekko** [comment]
fixed in #116
