### ISSUE TITLE
CodeGen: add Vuejs support

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#123]
- [x] add Component codegen
- [x] add spec file codegen
- [x] add HTML codegen
- [x] add styles codegen
- [x] add readme codegen
- [ ] add export to stackblitz
- [ ] add unit test
- [x] add entry to the editor menu

**Comment by Shikanime** [comment]
I will look for this impl.

**Comment by Shikanime** [comment]
Unfortunately, VueJS 2 can't be used in Stackblitz. 😫

**Comment by manekinekko** [comment]
Hey @ericsimons, any plans to add support for Vue 2 to stackblitz?

**Comment by EricSimons** [comment]
@manekinekko yeah! Should be ready by EOM

**Comment by manekinekko** [comment]
Related: https://github.com/stackblitz/core/issues/14

**Comment by manekinekko** [comment]
Fixed in #148
