### ISSUE TITLE
CodeGen: add Web Components support

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#124]
- [x] add Element codegen
- [ ] add spec file codegen
- [x] add HTML codegen
- [ ] add styles codegen
- [x] add readme codegen
- [x] add export to stackblitz
- [ ] add unit test
- [x] add entry to the editor menu

**Comment by romulocintra** [comment]
@manekinekko  already started playing wing WC' so easy to implement ... thinking about make plugable ... cause stenciljs , svelte , lit-element etc ...
