### ISSUE TITLE
Make the 3d design rotate

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#128]
**Describe the solution you'd like**
As an xlayers.app user, I want to be able to rotate the 3d design -presumably- using my mouse.

**Comment by sumitparakh** [comment]
I want to try this. @manekinekko

**Comment by manekinekko** [comment]
Please do :)

**Comment by manekinekko** [comment]
@sumitparakh any updates on this?

**Comment by sumitparakh** [comment]
> @sumitparakh any updates on this?

@manekinekko . Will give merge request in 2-3 days

**Comment by sumitparakh** [comment]
@manekinekko , I want to if there will be always one page in a file? If not, can you share me a sketch file which would generate two pages in xlayers? I just need to test something regarding this issue. 

![image](https://user-images.githubusercontent.com/4236211/53187528-58a0c100-3629-11e9-92f5-9ea41364e98d.png)

**Comment by manekinekko** [comment]
there will be files with multiple pages. Use this one as an example: https://github.com/xlayers/xlayers/files/2850149/card.test.copy.zip

**Comment by manekinekko** [comment]
Any updates on this? Need help?

**Comment by sumitparakh** [comment]
I'm outside now. Will share draft PR by Tuesday.
