### ISSUE TITLE
Better Code Export 

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#133]
**Is your feature request related to a problem? Please describe.**
Currently, when the users download or export their generated code into, ie: Stackblitz, the code that is exported is the one produced by the CodeGen service. At the same time, we show that code to the user inside the embedded Monaco editor. If the user decides to update that generated code, and then export that updated code to, ie: StackBlitz, they won't get their modified code but the original code from the CodeGen service.

**Describe the solution you'd like**
We should allow exporting and downloading the code, from the code editor not from the CodeGen directly.

**Comment by Shikanime** [comment]
@manekinekko It's a little tricky because we choose not to letting the user edit the design. Why should we let the user edit the code?
Or should we provide a code editor? (Deep questioning 🙇‍♂️)

**Comment by manekinekko** [comment]
no relevant anymore.
