### ISSUE TITLE
Move the parser into its own repository

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#134]
**Describe the solution you'd like**
We are planning some interesting features for xlayers but for that, we need to move the sketch parser into its own repository. 

The parser is written in pure TS so that should be easy.

**Comment by Shikanime** [comment]
@manekinekko I have two ideas for implementing a monorepo that I am still experimenting with, let me have your opinion:

- A monopero that I call "Hybridrepo" that I found more natural, I assume that "packages" are only libraries that can be externalised and keeping the Xlayers application at the root. ([hybridrepo](https://github.com/sfeir-open-source/xlayers/tree/refactor/hybridrepo))
- Classical monorepo wherer everything are package ([monorepo](https://github.com/sfeir-open-source/xlayers/tree/refactor/monorepo))

**Comment by Jefiozie** [comment]
Just sharing some thoughts after I had a look at both approaches. I believe there is a advantage on the monorepo example.

At this moment the only thing you want to extract is the parser. But if, for example you  want the editor to be independent it can be a separate package. 

Separating packages also forces to have a clean module implementation with specific boundaries.

Also wanted to point out that the angular CLI has a libraries option. Probably this is not the best suited option for this case.

**Comment by Shikanime** [comment]
@Jefiozie Thank you for your opinion, that make sense. I will explore this way ⛏

**Comment by Jefiozie** [comment]
@Shikanime, let me know if you need help. I worked with [NX](https://github.com/nrwl/nx) for a `monorepo` approach and this is working realy good. But if you want to publish separate packages I would go for something else.

**Comment by manekinekko** [comment]
@Jefiozie sorry for the delay. been preparing a talk. so for the monorepo story, as discussed with @Shikanime during our weekly meeting, we'll stick with the angular cli for the moment

**Comment by Jefiozie** [comment]
Thanks for the response! 👍
