### ISSUE TITLE
CodeGen: add StencilJS support

### ISSUE THREAD

**Issue by romulocintra** [xlayers/xlayers#137]
- [x] add Component codegen
- [ ] add spec file codegen (if applicable)
- [x] add HTML codegen
- [x] add styles codegen
- [x] add readme codegen
- [ ] add export to stackblitz
- [ ] add unit test
- [ ] add entry to the editor menu

**Comment by manekinekko** [comment]
@romulocintra thanks for open this rfc. Are you already working on this?

**Comment by romulocintra** [comment]
@manekinekko  yes I'm on it. Just started to get things working but i was trying to find a way to add more integrations without move so many pieces. templates starting getting big ,i'am refactoring in partials ... tomorrow I will drop propper descriptions for the tasks

**Comment by romulocintra** [comment]
Already added support on [REPO](https://github.com/romulocintra/xlayers/tree/feature/include-stenciljs) but wasn't able to run stencil code on stackblitz yet ... need to investigate

**Comment by manekinekko** [comment]
@romulocintra exporting a codegen to stackblitz is not mandatory. Users can still download a ZIP file with the generated code.

**Comment by romulocintra** [comment]
@manekinekko  ok will cleanup and update to raise PR 👍 but still wanting to see it running on Stackblitz ...

**Comment by manekinekko** [comment]
any ETA on this? I'd like to schedule this for v1.

**Comment by romulocintra** [comment]
During weekend will land the PR

**Comment by Shikanime** [comment]
Implemented by #160
