### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by goodmite** [xlayers/xlayers#141]
I am sorry for this stupid question but I couldn't find a way to change edit the properties. All the inputs are disabled. Please see screenshot.
Thanks.
<img width="960" alt="gh" src="https://user-images.githubusercontent.com/16303528/50386521-4b8d5180-070e-11e9-80f7-a0fb69565696.png">

**Comment by manekinekko** [comment]
Hi, this is the expected behavior. The properties are not meant to be edited.

**Comment by sangupta007** [comment]
So do I use it. Individual elements aren't draggable as well. If I want to increase font size, how do I do that? Is there any video or GIF on usage. Thank you.

**Comment by Shikanime** [comment]
Hi goodmite,
The main objective of Xlayers is to provide you with a tool to generate agnostic components from your Sketch project, not to replace SketchApp itself.
We think as a good practice, if a modification is necessary, you should edit your Sketch directly.

Or if the view does not correspond to your expectation, then the parser may be in cause and an issue should be opened to be treated.
