### ISSUE TITLE
sketch file upload doesn't work

### ISSUE THREAD

**Issue by goodmite** [xlayers/xlayers#147]
**Describe the bug**
Trying to upload a sketch file via drag drop or manual. Doesn't work.

**To Reproduce**
Try to upload a sketch file

**Expected behavior**
Upload should work.

**Screenshots**
Video here: https://imgur.com/oOJrc7R

**Desktop (please complete the following information):**
 - Windows 10
Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**

**Comment by Shikanime** [comment]
Hello goodmite,

What is the SketchApp version of your file ?

**Comment by manekinekko** [comment]
@goodmite is your issue similar to this one https://github.com/xlayers/xlayers/issues/153?

**Comment by manekinekko** [comment]
Assuming that this issue is related to #153. This has been fixed in #159
