### ISSUE TITLE
Add a custom exception handler

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#150]
**Is your feature request related to a problem? Please describe.**
When an issue happens on prod and the app throws an exception, the error stack will show up in the console. We dont wanna ask the users to open the console and copy paste that stack trace. We need to help them with that.

**Describe the solution you'd like**
We need a custom exception handler that would catch that error and its stack trace and show it to the users inside, eg, a dialog. This would allow the users to easily copy the content of that trace so they can share it we the team and we can easily use that content to debug and fix any potential issue.

**Comment by Jefiozie** [comment]
@manekinekko can I take this one? Also I saw that you are using the Google Tag manager do you want the errors of production to be send there?

**Comment by manekinekko** [comment]
Google tag manager can be added later. For the moment, we are just looking to have a centralized error handling and hook the notification manager with it.

**Comment by Jefiozie** [comment]
Hi, looking at this issue I see that you are using `@bugsnag/plugin-angular` at the moment for the errorhandling.  Would you like me to use this as a base and extend it by informing the users with the error message by using the notification manager?

**Comment by manekinekko** [comment]
sure. Let's try this.

**Comment by manekinekko** [comment]
Hi @Jefiozie any updates on this?

**Comment by Jefiozie** [comment]
hi @manekinekko, I didn't find the time to have a look at it. Hope I can get started upcoming week.

**Comment by Jefiozie** [comment]
Hi @manekinekko , just added the PR. Let me know what you think about it.
