### ISSUE TITLE
VS Code Plugin

### ISSUE THREAD

**Issue by romulocintra** [xlayers/xlayers#163]
Just having similiar functionality that we have on the web , but from a vscode plugin where you can drag drop your sketchfile and it will generate the files you need to run component/app/project

**Describe the solution you'd like**
I see that would be similar functionality like is already there in download part , but with aditional files like package.json , ts-config that are missing in donwload, cause we introduce them later when exporting to stackblitz.

Probably could be a 2 step implementation : 

1 -Solve donwload converted sketch with additional files to run the app (pkg.json , etc. ..)
2 - Mimic same behaviour as VS code component

**Comment by Jefiozie** [comment]
To keep everybody posted on this topic, we have created a separate repo for this [xlayers-vscode-extension](https://github.com/xlayers/xlayers-vscode-extenstion). Here you can create issues for bugs, feature request. We did not yet publish it to the marketplace. This is coming soon :)  for now I will close this issue as we have the separated repo.
