### ISSUE TITLE
Automate the CHANGELOG

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#172]
Use https://github.com/conventional-changelog/conventional-changelog

**Comment by manekinekko** [comment]
Must be done with #166

**Comment by Jefiozie** [comment]
When #134 has been done I can have a look at this issue.
Do we need to do something around checking the commit message? Probably we want to be sure that the correct commit message format is being used?

And do we want to generate a changelog for each package or in total?

**Comment by manekinekko** [comment]
Commit messages are verified when a PR is created (on github). I dont think we need to double check that on the developer machine. Do we?

> And do we want to generate a changelog for each package or in total?
It would be great to have a changelog file per project.

**Comment by Jefiozie** [comment]
I still don't know why but the duplicate items in the changelog are really different commits. See the examples below.

![image](https://user-images.githubusercontent.com/17835373/52585035-034bff00-2e34-11e9-871a-36a49c4f4bb2.png)


![image](https://user-images.githubusercontent.com/17835373/52585042-0a730d00-2e34-11e9-9a37-8b485df12546.png)


>Commit messages are verified when a PR is created (on github). I dont think we need to double check that on the developer machine. Do we?

The advantage of using tools as [commitizen](https://github.com/commitizen/cz-cli) and [commitlint](https://github.com/conventional-changelog/commitlint) is that you will have a good history of git commits on wich you can generate the changelog. For example `RxJs` is also using one of these tools [rxjs](https://github.com/ReactiveX/rxjs/blob/master/package.json#L8)


>It would be great to have a changelog file per project. 

It is possible to generate seperate changelogs. However there is a downside, if you want to use this in one repo to show user where the changes are they need to have a look at two seperate changelog file. 
 
- Project A
	--> Changelog.md
- Project B
	--> Changelog.md

But if we use one file and a good commit lint strategy you will get something like [ngrx changelog](https://github.com/ngrx/platform/blob/master/CHANGELOG.md) multiple projects with one changelog with specifc changes for specific scopes.
