### ISSUE TITLE
Sketch 53 with text-preview will resolve as unsupported.

### ISSUE THREAD

**Issue by Jefiozie** [xlayers/xlayers#176]
**Describe the bug**
When using the new version of sketch v 53 it will not work with Xl
[card test copy.zip](https://github.com/xlayers/xlayers/files/2850149/card.test.copy.zip)

ayers.
Had a quick look and it looks like in some specific cases there is a `text-preview` option with a PDF in it. The parser doesn't handle this well.

**To Reproduce**
1. Open the file in xlayers and see the result. 
 
**Expected behavior**
Handles the file and maybe ignore the pdf preview? 

**Screenshots**

**Sketch (please complete the following information):**
- version: 53

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: [e.g. 22]

[card test copy.zip](https://github.com/xlayers/xlayers/files/2851408/card.test.copy.zip)

**Comment by manekinekko** [comment]
A PDF! Holy sh***. Thanks for reporting this. Good catch. We now have 2 options:
1. Write or use a PDF parser
2. Or ignore it.

cc @Shikanime

**Comment by Jefiozie** [comment]
Happy to help btw, I have asked our designer why this is in the output. He had no specif changes.. he just upgraded to version `53`.

**Comment by Jefiozie** [comment]
Added a Sketch file with the problem 👍

**Comment by manekinekko** [comment]
We can't blame Bohemian B.V. for doing this. We just have to follow along 🤷‍♀️

**Comment by manekinekko** [comment]
Hi @Jefiozie I went with option 2. Now we can decode the PDF previews from the SketchApp file. Please give it a try and let me know. Cheers.

See #177
