### ISSUE TITLE
Autofix layer position doesn't work

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#178]
**Describe the bug**
When loading a sketch design which hasn't been set to top:0 and left:0. We normally dispatch the `AutoFixPagePosition` action (in the store) that is supposed to reset the x and y position of the outer frame to 0. This doesn't seem to always work.

**To Reproduce**
1. Open a sketch design with a top and left different than 0
2. The design should render out of the viewport. You then have to either zoom out to see the design or resize your screen (if you have a bigger screen)

**Comment by Shikanime** [comment]
@manekinekko Can you provide a sample file ?

**Comment by manekinekko** [comment]
[card.test.zip](https://github.com/xlayers/xlayers/files/2864545/card.test.zip)

**Comment by Shikanime** [comment]
Implemented by #186

**Comment by manekinekko** [comment]
Fixed in #186
