### ISSUE TITLE
UI designer tool: add support for InVision

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#193]
InVision project file `.studio` seems to have to same file structure as SketchApp `.sketchapp`.

https://www.invisionapp.com/#tour

**Comment by Jefiozie** [comment]
Here is a basic "Square" designed within `Invision Studio`.

[square.zip](https://github.com/xlayers/xlayers/files/2918400/square.zip)

**Comment by manekinekko** [comment]
Due to the lack of engineering time, I suggest dropping support for Adobe XD in favor of Figma support. We will reopen this issue if needed.
