### ISSUE TITLE
Remove PDF previews from side bar

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#200]
@Shikanime has done a deep analysis of this feature yesterday, and here is his conclusion:
- since v53, SketchApp has now a new entry containing a PDF document with one or many pages of different preview assets (font, layers...etc).

-  With that being said, this is not really **the** main preview of the document. The main preview of the design is still in the `preview.png` file and we should always take that preview into account.

- The PDF previews will be parsed but not shown in the UI (for the time being).

**Comment by Jefiozie** [comment]
This feature was recent implemented in #177. Why do we want it removed?

**Comment by manekinekko** [comment]
@Jefiozie I've updated the description with more context.

**Comment by Jefiozie** [comment]
Thanks this makes more sense.

> With that being said, this is not really **the** main preview of the document. The main preview of the design is still in the `preview.png` file and we should always take that preview into account.

Agreed on this point! 👍 	

> The PDF previews will be parsed but not shown in the UI (for the time being).

Why should we leave it in the parser? I think our end users would like to have a basic preview and the generated code. This is why they are using Xlayers. A pdf extra is not really needed. 

But this is my point of view and I'm not really an expert on what we should or should not add to Xlayers.

**Comment by manekinekko** [comment]
> Why should we leave it in the parser?

What I meant by this is that we need to take this new entry into account and parsing, and eventually ignore it, otherwise we will end up with the same issue as in https://github.com/xlayers/xlayers/issues/176

> But this is my point of view and I'm not really an expert on what we should or should not add to Xlayers.

xLayers is a community driven projet, your opinons and feeback matter a lot 😄

**Comment by Jefiozie** [comment]
I forgot about #176, thanks for the feedback!
