### ISSUE TITLE
Landing page better UX and UI design

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#234]
**Is your feature request related to a problem? Please describe.**
Our current landing page could get some refresh to take advantages of wide screen.

![image](https://user-images.githubusercontent.com/1699357/53766980-b27c7300-3ed4-11e9-801a-1350e02e30bf.png)

Any suggestions?

**Comment by Shikanime** [comment]
We should also redo all the previews since they have been updated and are more accurate.

**Comment by jacobtyq** [comment]
I will try working on this, forking the repository
