### ISSUE TITLE
Zoom buttons should be highlighted when active

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#237]
**Describe the bug**
When the zoom buttons are active (zoomed in/zoomed out) they are not highlighted as such (red UI).

**Expected behavior**
The zoom buttons should be highlighted as active (red UI) when they are used.

**Screenshots**
![screencast 2019-03-04 23-43-12](https://user-images.githubusercontent.com/1699357/53767951-ac3bc600-3ed7-11e9-8fe2-d7a20eec1d33.gif)

**Comment by Jefiozie** [comment]
This one can be closed as #255 is merged. Or is there still some work we would like to do on this topic?
