### ISSUE TITLE
Add e2e test suites for Cypress

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#238]
**Is your feature request related to a problem? Please describe.**
We wanna start to have e2e test for most main feature of xLayers.

**Describe the solution you'd like**
Have a set of e2e tests written using Cypress (already setup) that would test the following specs:

Landing:
- [x] [E2E-LA1]: the landing page should render the getting started button
- [x] [E2E-LA2]: the getting started button should open the upload

Editor:
- [ ] [E2E-ED1]: the editor page should render and use the drag and drop area
- [ ] [E2E-ED2]: the editor page should render and use the upload button
- [x] [E2E-ED3]: the editor page should render and use the demo files list

Interactions:
- [x] [E2E-INT1]: when loading a design file, the left sidebar should render and shows the correct layers structure
- [x] [E2E-INT2]: when selecting a layer in the left sidebar, the design should highlight the correct layer in the canvas are
- [x] [E2E-INT3]: when selecting a layer of a design file, the left sidebar should highlight the correct layer
- [x] [E2E-INT4]: when selecting a layer of a design file, the right sidebar should show up
- [ ] [E2E-INT5]: when selecting a layer of a design file, the right sidebar should render the preview, properties...etc
- [x] [E2E-INT6]: when using the toolbar buttons (zoom, layers...etc) the design canvas should react accordingly

Code Editor:
- [ ] [E2E-CODE1]: when selecting a technology in the drop down menu (eg. angular or vue), the editor should render the correct codegen output.

Any other suggestions are more than welcome.

⚠️**NOTE: Please make sure you submit one PR per scenario**⚠️

**Comment by krvajal** [comment]
I want to do this. Can I claim the issue?

**Comment by Jefiozie** [comment]
Hey @krvajal, yes you can and thank you! Let me know if you have any problems.

**Comment by manekinekko** [comment]
@krvajal thanks for helping with this issue. Can you let us know which scenario you are working on? and can you make sure you submit one PR per scenario? 🙏🏻

**Comment by krvajal** [comment]
Sure, I am working on setting up cypress first and updating the CI config to run the tests. I will have a PR ready later today.

**Comment by Jefiozie** [comment]
hey @krvajal, any updates on this issue? Are you facing problems we can help you with if so please let u know.

**Comment by krvajal** [comment]
Hey folks, I created an initial PR here ☝️ . I will like to get some feedback.
