### ISSUE TITLE
zoom: even if the scrollbar is necessary does not appear

### ISSUE THREAD

**Issue by gioboa** [xlayers/xlayers#24]
**Describe the bug**
Even if the scrollbar is necessary does not appear.

**To Reproduce**
1. Open `md-components-cards-safari.sketch` demo file
2. Click zoom button
3. Scrollbar does not appear

**Screenshots**
![no-scroll](https://user-images.githubusercontent.com/35845425/45031717-e541cd80-b04f-11e8-8635-cae5c8e50ee0.gif)

**Desktop (please complete the following information):**
 - OS: macOs High Sierra
 - Browser: Chrome
 - Version: 68

**Comment by daniloff200** [comment]
I have a solution, but, it looks a little bit not completely proper, I should say.

Check out my gif.

I can scroll after the zooming in, but, when I can't scroll up, to the content, which I don't see
For example, I zoomed in a datepicker, then zoomed it again, and can scroll for the whole viewport, but can't see what is on the top. The only way to do it - zoom out again...

![peek 2018-09-05 22-47](https://user-images.githubusercontent.com/13692220/45117300-e19c6c80-b15d-11e8-99c7-d24bb83f862f.gif)

Need to investigate more, I think

**Comment by gioboa** [comment]
I had investigate and I think the problem is where is used
`translate3d(-50%, 50%, 0px) scale(${zoomLevel})`
Maybe in a different element we have a better result.
So weird, not easy to fix it. :thinking:

**Comment by manekinekko** [comment]
What about increasing the margins while zooming in (and decreasing while zooming out), which will give us some room to scroll up and down and keeping the content in the viewport?

**Comment by manekinekko** [comment]
fixed by https://github.com/xlayers/xlayers/pull/62
