### ISSUE TITLE
Explore embedding Stackblitz into xLayers

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#240]
**Is your feature request related to a problem? Please describe.**
We could embed Stackblitz into xLayers editors for seamless integration. See docs: https://stackblitz.com/docs#embedding

**Comment by Jefiozie** [comment]
Reference for myself: https://codesandbox.io/docs/importing#define-api

**Comment by Jefiozie** [comment]
reference: [code-server](https://github.com/codercom/code-server)

**Comment by Jefiozie** [comment]
Closing this down as explained in the PR.
