### ISSUE TITLE
Preview border offset

### ISSUE THREAD

**Issue by Shikanime** [xlayers/xlayers#249]
**Describe the bug**
Using border CSS, move everything by 1px bottom-right for each layer.

**Expected behavior**
Using outline instead

**Screenshots**
![image](https://user-images.githubusercontent.com/22115108/53889719-2dee3980-4027-11e9-9e27-c2b5216f39f7.png)
![image](https://user-images.githubusercontent.com/22115108/53889725-334b8400-4027-11e9-99b3-3d412c82af4b.png)

**Sketch (please complete the following information):**
- version: 52

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version: 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)

**Comment by manekinekko** [comment]
We also can use box-shadow to simulate borders:


With border | With box-shadow
-- | --
border: 1px solid red | box-shadow: inset 0 0 0 -1px red
border-top: 1px solid red | box-shadow: inset 0 1px 0 0 red
border-right: 1px solid red | box-shadow: inset -1px 0 0 red
border-bottom: 1px solid red | box-shadow: inset 0 -1px 0 0 red
border-left: 1px solid red | box-shadow: inset 1px 0 0 red
