### ISSUE TITLE
React cannot be exported to StackBlitz.

### ISSUE THREAD

**Issue by Jefiozie** [xlayers/xlayers#279]
**Describe the bug**
Using the generated `React` code in Stackblitz results in a error.

**To Reproduce**
1. Go to the 'code-editor'
2. Click on 'Choose Framework'
3. Click on the 'React' framework
4. Click on `Open project in StackBlitz`
5. See error

**Expected behavior**
Project should be exported to StackBlitz
 
**Screenshots**
![image](https://user-images.githubusercontent.com/17835373/54512909-07e56500-4956-11e9-8d4a-07a8c5de9b28.png)

**Comment by manekinekko** [comment]
Maybe a related issue: https://github.com/facebook/create-react-app/issues/748
