### ISSUE TITLE
Linting does not work correct on Windows

### ISSUE THREAD

**Issue by Jefiozie** [xlayers/xlayers#280]
**Describe the bug**
When running linting on commit it does not work correctly on `Windows`

**To Reproduce**
1. Change a file
2. Commit it to git
3. See error

**Expected behavior**
The linting should run normal.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Jefiozie** [comment]
To bypass this problem people can use the following steps:

1. Run `ng lint --fix`
2. Resolve issues that are comming from linting and add changed files to Git with `git add`
3. Commit the changes with bypassing the lint-staged step with following command: `git commit -m "MESSAGE" --no-verify`

**Comment by Jefiozie** [comment]
For reference:

[lint-staged](https://github.com/okonet/lint-staged/issues/547)
[angular cli](https://github.com/angular/angular-cli/issues/13078)

**Comment by AndreiShostik** [comment]
JFYI. 
I've commented a workaround here https://github.com/okonet/lint-staged/issues/547#issuecomment-534191338
despite this workaround I would suggest to use `tslint` directly as it is much faster. an investigation process you can find by a link above
