### ISSUE TITLE
CodeGen: add Xamarin.Forms support

### ISSUE THREAD

**Issue by t-dambacher** [xlayers/xlayers#283]
- [ ] add Component/Controler logic
- [ ] add spec file (if applicable)
- [ ] add HTML/XML/View (if applicable)
- [ ] add styles
- [ ] add readme
- [ ] add export to stackblitz (or other external editor)
- [ ] add unit test
- [ ] add entry to the editor menu

Hi everyone,

As a (mainly) .NET developer, I would love to have the support of Xamarin.Forms in xLayers, as it will help me creating new app faster. 
I work at @sfeir with @lopezarnaud, and we both have some free time ahead of us, thus would love to contribute and implement this. Would it be an interesting feature ?

**Comment by manekinekko** [comment]
Hi @t-dambacher we would love to add support for Xamarin.Forms. We are looking forward to your PR
