### ISSUE TITLE
Move the home folder to /src

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#286]
**Describe the solution you'd like**
We would like to move the landing page, which is in `packages/xlayers/src/app/home/` to the `/src` root folder. This would help us separate the landing page from the actual `packages/xlayers` app.

**Comment by Shikanime** [comment]
I will take it.

**Comment by Shikanime** [comment]
@manekinekko To be sure you want to move it to the `packages` dir or `xlayers/src` dir ?

**Comment by manekinekko** [comment]
Yes, xlayers/src.
