### ISSUE TITLE
Remove all Sketch reference from DOM elements and attr

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#287]
**Describe the solution you'd like**
We need to remove all `sketch` references from HTML element name, attributes, and Angular components/Directives class names (+ test files). 

For instance:

- Element names: `sketch-viewer-container` --> `xly-viewer-container`
- Classe names: `SketchPreviewComponent` --> `PreviewComponent`
- Directive names: `SketchStopEventPropagation` --> `xlyStopEventPropagation`

General Guidelines:

1. For HTML element names, use the `xly-` prefix, eg. `xly-preview`
2. For Angular class components/directives, remove the `Sketch` prefix, eg. `PreviewComponent`
3. For Angular directive names, use the `xly` prefix, eg. `xlyStopEventPropagation`
4. For CSS, use the `xly` prefix.

Related files:

- `find ./packages/xlayers \( -name "*.html" -o -name "*.ts" -o -name "*.css" \) -exec cat {} \; | grep "sketch"`
- `find ./packages/xlayers -iname "*sketch*"`:

**Comment by Shikanime** [comment]
Do that also concern the SketchParser?

**Comment by manekinekko** [comment]
Nope. Just xlayers. The current sketch parser was done for SketchApp.
