### ISSUE TITLE
add support for Sketch Symbols

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#295]
Use this design file which contains a design that is a symbol instance.
[symbol-demo.sketch.zip](https://github.com/xlayers/xlayers/files/3045596/symbol-demo.sketch.zip)

**Comment by Jefiozie** [comment]
I will assign my self for now so that anybody can pick this up. For now I will probably pick up smaller issues that I can fix within a couple of hours as this fits better in my agenda.

**Comment by manekinekko** [comment]
Hey @Jefiozie I think this feature has been added in #303. I think we can close this issue.

**Comment by Jefiozie** [comment]
I think you are right.
