### ISSUE TITLE
translate pointers on landing page

### ISSUE THREAD

**Issue by Jefiozie** [xlayers/xlayers#311]
I forgot the translation of the pointers on the landing page. This needs to be translated.
![image](https://user-images.githubusercontent.com/17835373/59918083-f794c880-9423-11e9-8f13-c420a056f3b7.png)

**Comment by sumitparakh** [comment]
Hi @Jefiozie , I see that the translations are already there. If so, can we close this issue?  Let me know if i am missing something. 

![image](https://user-images.githubusercontent.com/4236211/60387967-5dd6b680-9ac8-11e9-9b6d-3c27b210b214.png)

**Comment by Jefiozie** [comment]
Hi @sumitparakh, thank for looking into this. It looks like you are right (based on your screenshot) when I'm back from some time off I will have a look at it.

**Comment by Jefiozie** [comment]
Hi @sumitparakh, I just had a look at this issue and the issue is a valid issue. Is it possible that you have an extension that is translating text for you and this is the result?

Would you like to help me out with this issue? I can guide you through the parts that need to be changed to get the correct way of translating these pointers.

Let me know what you think about it.

**Comment by sumitparakh** [comment]
> Hi @sumitparakh, I just had a look at this issue and the issue is a valid issue. Is it possible that you have an extension that is translating text for you and this is the result?
> 
> Would you like to help me out with this issue? I can guide you through the parts that need to be changed to get the correct way of translating these pointers.
> 
> Let me know what you think about it.

Got it. I'll fix it today.

**Comment by Jefiozie** [comment]
Great! 🙏 If you need my help or have any questions just ping me on Slack.
