### ISSUE TITLE
Upgrade to Angular V8.3

### ISSUE THREAD

**Issue by Jefiozie** [xlayers/xlayers#327]
We would like to be on the latest Angular version. This means that we should update xlayers and the dependencies like ngxs.

As the most of our code is Angular, it will be easy to do the upgrade by using the 'ng update' command from the cli.

**Comment by kartik-budhiraja** [comment]
@Jefiozie I would like to work on this issue if it's available.

**Comment by Jefiozie** [comment]
Hi @kartik-budhiraja, thank you for replying, you can work on it if you want. If you need any help just leave a comment and I will do my best to help you.

**Comment by kartik-budhiraja** [comment]
@Jefiozie We are aiming to upgrade only angular modules like CDK, cli, core, or are we aiming to upgrade every dependency which has a newer version?

**Comment by Jefiozie** [comment]
@kartik-budhiraja our main focus should be on the `Angular` and dependencies that relate to the  `@angular/core`. For example `@ngxs/store` is depending on `@angular/core` so probably we should upgrade this as well. 

The angular package can be easily upgraded by using the `ng update <package>` command. The others probably need some manual upgrades.

**Comment by kartik-budhiraja** [comment]
@Jefiozie `ng update <package>` command currently has a bug where it updates rest of the dependencies to beta versions, according to this [comment](https://github.com/angular/angular-cli/issues/14980#issuecomment-523600333) updating dependencies manually in package.json has been suggested. I created a PR #332 with the changes.

**Comment by Jefiozie** [comment]
Thanks for helping us with this issue and thanks for having a look at the reason `ng update` command did not work. Already reviewed your PR and it looks good! Thank you 🙏🏻
