### ISSUE TITLE
Could not load a Sketch preview "images/853732577995ec08625706620b0235b0184b90e8.png"

### ISSUE THREAD

**Issue by coopdesis** [xlayers/xlayers#346]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Sketch (please complete the following information):**
- version: [e.g. 52]

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by Jefiozie** [comment]
Hi @coopdesis thank you for reporting this issue. Could you add the information to reproduce the bug? Would be nice if you could add the sketch file if possible.

Thanks

**Comment by manekinekko** [comment]
Hi @coopdesis thanks for opening this issue.

could you please fill in the rest of the info in order to help us better understand your issue. Cheers.

**Comment by Jefiozie** [comment]
Hi @coopdesis, any updates on this issue?

**Comment by Jefiozie** [comment]
Hey @coopdesis, for now I'm closing this issue. Please fill free to reopen it in case you have the information and you can provide it to us. Thanks
