### ISSUE TITLE
Could not load a Sketch preview "images/853732577995ec08625706620b0235b0184b90e8.pdf"

### ISSUE THREAD

**Issue by swarburt** [xlayers/xlayers#351]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Sketch (please complete the following information):**
- version: [e.g. 52]

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by manekinekko** [comment]
Hi, could you please provide more details so we can investigate your issue?

**Comment by swarburt** [comment]
trying to ingest a sketch file. immediatly after dragging the file to the upload area the error message appears.

-Sherry

**Comment by Jefiozie** [comment]
Hi, could you provide us more details on what sketch version you are using and is it possible to share the sketch file?

**Comment by swarburt** [comment]
sketch version 53
file size 4.2Mb

Sorry I can not share the sketch file as we are a stealth startup and this forms one of our key front ends.

-Sherry

**Comment by manekinekko** [comment]
Closing. Please reopen an issue if the problem persists. Thank you.
