### ISSUE TITLE
SyntaxError: Unexpected token a in JSON at position 0

### ISSUE THREAD

**Issue by TanuJohari1312** [xlayers/xlayers#353]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Sketch (please complete the following information):**
- version: [e.g. 52]

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by sumitparakh** [comment]
Hi @TanuJohari1312,  Thanks for opening this issue.Would you please add sepcific details about this bug like in which case you faced this issue, which browser, version, device and if possible, sketch file as well?  
Thanks.

**Comment by Jefiozie** [comment]
I'm closing this issue, for now, to keep our issue tracking clear. If needed you're more then welcome to reopen or file a new issue. Thanks for understanding.
