### ISSUE TITLE
TypeError: Cannot read property 'point' of undefined

### ISSUE THREAD

**Issue by 465media** [xlayers/xlayers#355]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Sketch (please complete the following information):**
- version: [e.g. 52]

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by manekinekko** [comment]
Hi, could you fill in the missing details in the issue template, so we can investigate this issue?

**Comment by Jefiozie** [comment]
I'm closing this issue, for now, to keep our issue tracking clear. If needed you're more then welcome to reopen or file a new issue. Thanks for understanding.
