### ISSUE TITLE
Color generation is not working on Firefox (Windows)

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#359]
**Describe the bug**
When you use firefox and open up a sketch demo file sometimes it is missing the correct colors.
It looks like this is a issue with Firefox and windows.

**To Reproduce**
1. Go to [xlayers.dev](https://xlayers.dev)
2. Click on `Get Started`
3. Click on `Select a demo file`
4. Click on the first sketch file
5. See missing colors in the card example

**Expected behavior**
We should have a correct colored example

**Screenshots**
![image](https://user-images.githubusercontent.com/17835373/94999044-c14a7080-05b6-11eb-82f1-b453d6f2cf78.png)

**Sketch (please complete the following information):**
- version: 59

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser: [e.g. chrome, safari] Firefox 
 - Version: [e.g. 22] 81.0.1

**Additional context**
If you need any more information or help ping me (@Jefiozie )

**Comment by Jefiozie** [comment]
This issues could be related to #373, when the PR is finished we are going to see if this error is still in place.

**Comment by manekinekko** [comment]
Fixed in https://github.com/xlayers/xlayers/commit/89a72d30bf91525222a96c0d0cb011c705949d89
