### ISSUE TITLE
Convert the stamp script to Node.js for more interoperability

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#366]
Our builds are currently failing on Windows because the [stamp.sh](https://github.com/xlayers/xlayers/blob/main/scripts/stamp.bash) does not run on windows.

We'd like to migrate the [stamp.sh](https://github.com/xlayers/xlayers/blob/main/scripts/stamp.bash) script to a Node.js script to be able to run on different OS.

**Comment by Jefiozie** [comment]
I'm closing this issue as there is a PR(#367 ) already merged
