### ISSUE TITLE
CSS generation : size/color value conversion

### ISSUE THREAD

**Issue by anediaz** [xlayers/xlayers#368]
**Is your feature request related to a problem? Please describe.**
Currently, we codegen CSS code for styling.

**Describe the solution you'd like**
In the generated CSS code, multiple values, like sizes in pixels (or other units), colors in RGBA ... are not converted in a realistic way. For instance :
- sizes with multiple decimal digits :  -0.00000201463535631774px;
- sizes with exponential values :  -3.019895302713849e-7px;
- colors with decimals : rgba(0,0,0,0.54);
(source: generated datepicker demo file)

It'd be preferable to adapt these values during the CSS generation process in order they respect value formatting rules.

**Comment by manekinekko** [comment]
Fixed in https://github.com/xlayers/xlayers/commit/89a72d30bf91525222a96c0d0cb011c705949d89
