### ISSUE TITLE
Display generated file's original name

### ISSUE THREAD

**Issue by anediaz** [xlayers/xlayers#369]
****Is your feature request related to a problem? Please describe.****
Currently, after having selected a SketchApp file to be converted, the preview screen does not show imported file's name.

**Describe the solution you'd like**
I'd be nice to display the file's original name, for example on the left side of the editor, in the top of the lateral column, in order to know which file we are working with.

**Comment by anediaz** [comment]
I've started to work on this issue.
I hesitate about where to place the file's original name : On the top horizontal bar (editor component) or the left side panel (preview component), or another place?

**Comment by Jefiozie** [comment]
Personally I find the one with the filename in the top pretty nice. I would remove the `.sketch` part, this way people only see the name. @manekinekko what do you think?

**Comment by anediaz** [comment]
> Personally I find the one with the filename in the top pretty nice. I would remove the `.sketch` part, this way people only see the name. @manekinekko what do you think?

I agree with you, I think it'll be better without the extension. I hope juste it is clear enough, I mean, users will understand it is original file's name

**Comment by manekinekko** [comment]
I also like having the name in the top toolbar. However, I think we also should add an icon based on the file type. For the context, we currently use SketchApp and *.sketch files, but we are planning on adding more design tools. So having the icon of the app (before the file name) would help users quickly identify which design file they are using.

**Comment by anediaz** [comment]
This is an excellent idea, I strongly believe the use of visual elements will improve the user experience!

I'll think about a structure that contains information of all the file types xlayers is compatible with, information we may need for this feature but also future. 
- Application/file type name
- Extension
- Logo (or the way to get it)
- Supported or compatible versions with xlayes
...

In addition, it will be possible to update it later if we need other informations that we have not included yet.

What do you think about it?

**Comment by manekinekko** [comment]
Sounds good. Can you make a proposal?

**Comment by anediaz** [comment]
You can take a look to my branch : https://github.com/anediaz/xlayers/tree/display-original-filename-in-editor
I've created a file named 'compatible-files' which is resposible for giving information about a file based on its name.
I have to fix a cypress test and I'll be ready to create a Merge Request.

It looks like this :
![xlayer1](https://user-images.githubusercontent.com/17216937/96456606-fbef1280-121e-11eb-86a2-77a1e49dc989.png)
![xlayer2](https://user-images.githubusercontent.com/17216937/96456616-feea0300-121e-11eb-819f-fc0a28934894.png)

**Comment by manekinekko** [comment]
This looks great!

I am wondering if we should explicitly show the version number? maybe we can show it as a title on mouse over the icon? Or something like that?

Because some other software might have some long version numbers like **56.32.5582**

WDYT?

**Comment by anediaz** [comment]
Yes I agree, it would be better showing explicitly the version number, without charging the screen too much.
I think giving this information is important, but it is not something the user wants to see in a first view.
So I think the mouse over action will be appropriate to show this kind of information.

In addition, currently version number returned by 'supported-files.ts'  is used nowhere, so I think your remark makes even more sense.

**Comment by anediaz** [comment]
Hello,
I think we can close this issue. My PR has been merged since some weeks, I've checked : https://xlayers.dev/
and I see that file's icon is present, but not the version number on mouse over. I think it is related to build cycle.

**Comment by Jefiozie** [comment]
Thank you pointing this out, I will close the issue.
