### ISSUE TITLE
Convert demo files to Sketch v69 

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#382]
We'd love to convert the existing demo files ([here](https://github.com/xlayers/xlayers/tree/main/apps/xlayers/src/assets/demos/sketchapp/59)) into the latest version of Sketch (v69).

## How-to
1. Open all demo files in Sketch v69.
2. Save the files back to disk, under **apps/xlayers/src/assets/demos/sketchapp/69**.
3. Commit and push your changes.

Thank you ❤️

**Comment by anediaz** [comment]
I've just created the PR

**Comment by manekinekko** [comment]
Hey @anediaz you can edit the environment files and create a new entry in the array. Here is the new entry to create:

```
{
      value: 69,
      disabled: true,
      files: [
        'md-components-notifications-heads-up',
        'md-components-cards-welcome-back',
        'md-components-tabs-status-bar',
        'md-components-cards-safari',
        'md-components-date-picker',
        'md-components-chips-open-chip',
        'md-components-cards-homes',
        'md-components-buttons-lights',
        'md-components-cards-pooch',
        'md-components-buttons-fabs-light',
      ],
    },
```

Here are the files:
- https://github.com/xlayers/xlayers/blob/main/apps/xlayers/src/environments/environment.hmr.ts#L11-L26
- https://github.com/xlayers/xlayers/blob/main/apps/xlayers/src/environments/environment.prod.ts#L11-L26
- https://github.com/xlayers/xlayers/blob/main/apps/xlayers/src/environments/environment.ts#L11-L26

**Comment by anediaz** [comment]
Yes no problem. As I've only followed your first advice I was surprised this part was forgotten

**Comment by manekinekko** [comment]
Fixed in https://github.com/xlayers/xlayers/commit/df2c03011d0edd429958cf671d10513aa32705b0
