### ISSUE TITLE
TypeError: Cannot read property 'borders' of undefined

### ISSUE THREAD

**Issue by yamne-it** [xlayers/xlayers#389]
**Describe the bug**
A message error "TypeError: Cannot read property 'borders' of undefined" is raised when a demo file is selected on URL https://xlayers.dev/#/upload

**To Reproduce**
1. Go to 'https://xlayers.dev/#/upload'
2. Click on 'Select a demo file'
3. Scroll down to 'any demo file'

**Expected behavior**
I suppose to open the demo file

**Screenshots**
![image](https://user-images.githubusercontent.com/61476433/97489011-4aa75580-195f-11eb-937e-9784ac2ea34a.png)

**Sketch (please complete the following information):**
- version: N/A

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser: chrome
 - Version:  86.0.4240.111 (Official Build) (64-bit)

**Comment by manekinekko** [comment]
Thanks for reporting this issue. We will investigate it and keep you posted.

**Comment by anediaz** [comment]
I can investigate if you want :innocent:

**Comment by Jefiozie** [comment]
Go ahead @anediaz 😊 I will assign the issue to you. Thank you for looking into this.

**Comment by nasiruddin-saiyed** [comment]
@yamne-it  Did you found any solution ? Its still not working :-(

**Comment by yamne-it** [comment]
> @yamne-it  Did you found any solution ? Its still not working :-(

I have reported this issue and I haven't tried it again. I was waiting for some feedback since reading the comments above, @anediaz is looking into it. 
I suppose she will get back to us when she found the bug or maybe what I was doing wrong 😀

**Comment by anediaz** [comment]
Hello,
I'm sorry, I haven't had the time to look at this issue.
If you want to look at it you are welcome.
I'll try to look at it as soon as possible :-)

**Comment by anediaz** [comment]
Hello,
I've tried to reproduce the bug locally but I can't, I mean, everything works well.
I've tried with a macOs and with Ubuntu, and I don't see the message.
However, when I check in 'https://xlayers.dev/#/upload', it is present.

@nasiruddin-saiyed can you give me more information of the way to reproduce it please?
Thank you in advance,
Ane

**Comment by nasiruddin-saiyed** [comment]
Hello @anediaz, 
Sorry for late response, 
It's throwing error in 
`libs/css-codegen/src/lib/css-parser.service.ts`
while extracting **borders** from styles.

Attached image shows the exact line of error. 
![image](https://user-images.githubusercontent.com/32707579/104883132-456c0c80-598a-11eb-9221-62dec3f3d6b5.png)

**Note**: This error appears in production on few components while selecting any of the existing demo files. I've upload image while debugging.

**Comment by anediaz** [comment]
Thank you @nasiruddin-saiyed for all this information!
As I can't see the bug in my local machine your explanation will help me a lot!
I'll try to work on it the next days, and I'll let you know.

Thank you :-)

**Comment by anediaz** [comment]
Hello @nasiruddin-saiyed,
I have looked at the code and tried to debug the file you mentioned. I've selected one by one all the existing demo files but I can't reproduce the bug.

I don't know why sometimes ``styles`` is undefined, as it respects ``SketchMSLayer`` interface.
Everything looks good for me, so the only idea I have to avoid displaying this message is replacing this :

``const obj = (current as any).style.borders;``

by this: 

``const obj = (current as any).style && (current as any).style.borders;``

In ``libs/css-codegen/src/lib/css-parser.service.ts``

What do you think about it?
