### ISSUE TITLE
Continuous Integration (GitHub Action) is not doing what you think it is.

### ISSUE THREAD

**Issue by pqt** [xlayers/xlayers#399]
### Describe the bug
Hey, just a random GitHub action enthusiast that stumbled on your codebase.

There's an incorrect reference in the `node-version` usage to your `strategy.matrix` causing it to silently fail and use the incorrect node version without any indication.

### To Reproduce
- Make a PR to `main`
- Take a look at the GitHub action runner logs.

### Expected behavior
I would expect the GitHub actions to run on all permutations of the provided matrix of operating systems and node versions (13/14).

### Actual behavior
At the time of writing, this is the action I'm talking about: https://github.com/xlayers/xlayers/blob/9651446b8c4e501d92f47c563196f043bd86194c/.github/workflows/pr_on_development.yml

The `node-version` matrix is set, however, the action uses `matrix.node` and that's undefined, causing the setup of Node to _always be in the wrong version_.

**Code Sample for reference** - (<kbd>L18</kbd> `node-version` is set, <kbd>L20</kbd> & <kbd>L23</kbd> (second reference) `node` is used.
https://github.com/xlayers/xlayers/blob/9651446b8c4e501d92f47c563196f043bd86194c/.github/workflows/pr_on_development.yml#L15-L23

This is also verifiable by seeing that a version is not applied in the name of the step, as the action is instructed to do.

https://github.com/xlayers/xlayers/blob/9651446b8c4e501d92f47c563196f043bd86194c/.github/workflows/pr_on_development.yml#L20

### Screenshots
Node version `13.x` should be set, but it is running on `14.x`.
![](https://i.imgur.com/wWCcuG9.png)

### Additional context
Simply changing all `strategy.matrix.node-version` instances to `strategy.matrix.node` does the trick. **BE CAREFUL THOUGH**, you can't do a complete find-and-replace because the `actions/setup-node@v1` input _does expect `node-version`_.

**Comment by pqt** [comment]
There's also another issue but I won't be checking the scope of this.

https://github.com/xlayers/xlayers/blob/9651446b8c4e501d92f47c563196f043bd86194c/.github/workflows/pr_on_development.yml#L70-L100

On your `test` job your final step is named `Run lint` rather than `Run tests`, I assume it's just an oversight from some quick code duplication.

**Comment by Jefiozie** [comment]
Hi @pqt, thank you for pointing this out to us. I just created a draft PR #400 to handle this issue.

Thank you for creating this issue.

**Comment by pqt** [comment]
No problem! Love the way the steps were actually separated and I learned about the `needs` key in the process so thanks for that! It seemed only fair that I pointed out the issues I found when I put the action under the microscope.
