### ISSUE TITLE
Fix resizing Top and Left edges

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#4]
![2018-05-27 15_10_03](https://user-images.githubusercontent.com/1699357/40586590-815399d6-61c4-11e8-9748-63ca846a6a7a.gif)

**Comment by manekinekko** [comment]
@vitaliy-bobrov I reopened this because we're still having the issue (see gif below). 

![screencast 2018-09-04 23-29-15 2018-09-04 23_52_20](https://user-images.githubusercontent.com/1699357/45059815-9ae73d80-b09d-11e8-8274-fd36879be4b8.gif)

**Comment by Shikanime** [comment]
The top and left resize actually works on my pull request except for nested layers because of the layer top and left causes interdependence. Which produces the same problem as the current issue.

This means that the layer system may need to be restructured to make it work.
