### ISSUE TITLE
Migrate async to waitForAsync

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#409]
[`async`](https://angular.io/api/core/testing/async) from `@angular/core/testing` is deprecated in Angular v12. Migrate to [`waitForAsync`](https://angular.io/api/core/testing/waitForAsync)

See #410 for a wip example.

**Comment by SagarPandita0** [comment]
Hello, I would love to contribute!

**Comment by Nicoss54** [comment]
Hi, I did a Pull request with the necessary change

see: #412

**Comment by Jefiozie** [comment]
@manekinekko I think this one can be closed now that #412 has landed?
