### ISSUE TITLE
stackblitz export not working

### ISSUE THREAD

**Issue by sumitparakh** [xlayers/xlayers#427]
**Describe the bug**

**To Reproduce**
1. Select angular
2. Open any demo file
3. Go to code section
4. Click Stackblitz Export button.

**Expected behavior**
It should export generated code to the stackblitz and open it in the new tab.

**Actual behavior**
It throws console error

**Screenshots**
![image](https://user-images.githubusercontent.com/4236211/121952502-f0d28f00-cd79-11eb-9055-f206411d4bc3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Version: Latest

**Comment by sumitparakh** [comment]
Figured that it stopped working after this commit: https://github.com/xlayers/xlayers/commit/6aa399c31efe4f63b2bf71a298c7e25c54f1dac2

**Comment by manekinekko** [comment]
Thank you @sumitparakh for reporting and investigating this.

**Comment by manekinekko** [comment]
Are you able to provide a fix for this issue?

**Comment by sumitparakh** [comment]
@manekinekko I can try. Please assign this to me.
