### ISSUE TITLE
Add better designer support 

### ISSUE THREAD

**Issue by jogibear9988** [xlayers/xlayers#474]
I've created a WYSIWYG html designer (https://github.com/node-projects/web-component-designer). What do you think about the idea of integrating it, so the design could be adjusted before the code generation?
Would this be possible? At the moment I'm not very deep in the project, and for me it's not clear what is the basis from wich you then create the code for the different frameworks.

**Comment by Jefiozie** [comment]
Hi @jogibear9988 ,  thanks for submitting the issue and great work on your editor. I think we won't add this to our projects as the  project has not been pushed at this moment by the core contributor.

I hope you understand this and I will close the issue. If anything else pops up dont hesitate to open up a issue.
