### ISSUE TITLE
Canvas unit test fail

### ISSUE THREAD

**Issue by Shikanime** [xlayers/xlayers#71]
**Describe the bug**
The variable "isPreview" should have been remove before merging the https://github.com/xlayers/xlayers/pull/66 because it's now always null and not used anymore.
The newly introduced SketchSelectedLayerDirective fail the canvas unit test "should have current page", the reason is still unknow.

**To Reproduce**
1. Checkout fix/unit-test
2. Remove the test skip by replacing "fit" by "it" at line 47
2. Run "npm run test"

**Expected behavior**
Should success unit tests

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.1
 - Browser Firefox
 - Version 63.0.3

**Comment by manekinekko** [comment]
fixed https://github.com/xlayers/xlayers/pull/74
