### ISSUE TITLE
Cannot click on element anymore

### ISSUE THREAD

**Issue by Shikanime** [xlayers/xlayers#72]
**Describe the bug**
Cannot click on element anymore.
![screencast 2018-11-19 12-39-42](https://user-images.githubusercontent.com/22115108/48704972-41040780-ebf8-11e8-976d-995131562643.gif)

**To Reproduce**
1. Load a sketch file
2. Click on any element

**Expected behavior**
The tree structure should have shown the element and the right sidebar should have appeared.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.1
 - Browser Firefox
 - Version 63.0.3

**Comment by manekinekko** [comment]
Well! That's a new bug. I believe it was working for me yesterday on chrome.

**Comment by Shikanime** [comment]
After investigation. Except Google Chrome the "event.path" array used by the SketchSelectedLayerDirective is not supported by other browser.

**Comment by manekinekko** [comment]
this should be fixed in #75
