### ISSUE TITLE
CodeGen: add Svelte support 

### ISSUE THREAD

**Issue by mindrones** [xlayers/xlayers#89]
Hi, are there any plans to support [Svelte](http://svelte.technology/)?

Thanks!

**Comment by manekinekko** [comment]
Hi, once the codegen feature is ready, we can support any framework and lib.

**Comment by manekinekko** [comment]
@mindrones wanna help out with that? We can help you get started.

**Comment by mindrones** [comment]
Hi, are you going tu support the upcoming Svelte 3?

**Comment by manekinekko** [comment]
Let's start off with Svelte 2. And we'll update when 3 is released.

**Comment by manekinekko** [comment]
@mindrones wanna help out with this?

**Comment by LostInBrittany** [comment]
Hey @manekinekko can you give me some pointers to do it? I have been playing with Svelte for some time now, I think I could help here...

**Comment by sumitparakh** [comment]
Hi @manekinekko, may I work on it?

**Comment by manekinekko** [comment]
Hey @sumitparakh sure. Thank you!
