### ISSUE TITLE
No style on certain components after CodeGen

### ISSUE THREAD

**Issue by Shikanime** [xlayers/xlayers#93]
**Describe the bug**
The component is missing for the most part the button style or on a "group" class component.

![image](https://user-images.githubusercontent.com/22115108/50010746-84188700-ffba-11e8-91e2-b0c98c8e044f.png)

**Desktop (please complete the following information):**
 - OS: Mac Mojave 10.14.1 (18B75)
 - Browser Brave
 - Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

**Comment by manekinekko** [comment]
fixed in https://github.com/xlayers/xlayers/blob/d81b413c594bb436645a2293b2f9e60a52769f14/src/app/editor/code-editor/editor-container/codegen/angular/angular.service.ts#L150-L179
